#!/bin/bash

echo "File generated by the training pipeline (represents an MLflow run id) at \"ml_train@master\":"
pachctl list file ml_train@master
echo
echo "Pachyderm commit at \"ml_train@master\":"
pachctl list commit ml_train@master
echo
# echo
# echo "Related MLflow run id:"
# pachctl list file ml_train@master | awk '{print $1}' | tail -n 1 | cut -c2-
# echo
echo "Follow the link below to view the logged training run in MLflow:"
echo "http://127.0.0.1:30001/#/experiments/0/runs/"$(pachctl list file ml_train@master | awk '{print $1}' | tail -n 1 | cut -c2-)