apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow-server
        image: winderresearch/pachyderm-mlflow:0.1.0
        args:
            - --host=0.0.0.0
            - --port=5000
            - --default-artifact-root=s3://$(BUCKET)
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "foo_value"
          - name: AWS_SECRET_ACCESS_KEY
            value: "foo_value"
          - name: BUCKET
            value: "master.artifacts"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://pachd.pachyderm.svc.cluster.local:30600"
        ports:
            - containerPort: 5000
              protocol: TCP